---

- name: Check current configuration
  command: cat {{ tz_conf }}
  changed_when: false
  register: esc

- name: Print current configuration
  debug: var=esc.stdout_lines

- name: Update configuration file '/etc/sysconfig/clock'
  lineinfile: dest={{ tz_conf }} state=present backup=yes regexp='ZONE=.*' line='ZONE="{{ zone | mandatory }}"'
  notify:
    - show notes

- name: Set localtime '/etc/localtime'
  file: src=/usr/share/zoneinfo/{{ zone | mandatory }} dest={{ tz_file }} state=link force=yes
  notify:
    - show notes

# tzdata-update

- name: be sure latest 'tzdata' installed
  yum: name=tzdata state=latest
  when: ansible_distribution != 'Amazon'

- shell: tzdata-update
  when: ansible_distribution != 'Amazon'


