---

- name: Check current configuration
  command: cat {{ tz_conf }}
  changed_when: false
  register: esc

- name: Print current configuration
  debug: var=esc.stdout_lines

- name: be sure latest 'tzdata' installed
  yum: name=tzdata state=latest
  when: ansible_distribution == 'CentOS'

- name: Check if selinux is installed
  command: getenforce
  register: command_result
  ignore_errors: True

- name: be sure 'libselinux-python' installed
  yum: name={{ item }}
  with_items: 
    - epel-release
    - libselinux-python
  when: command_result|success and command_result.stdout != 'Disabled'

